---
latitude: 40.71918
longitude: -74.00165
map_zoom: 12
name: Soho Garden Hotel
email: sgontu@traveltripper.com
phone_number: 001-111-1111
address:
  street1: 276 Canal Street
  street2: ''
  state: New York
  city: New York
  country: United States
  zip_code: '10013'
_hotel_id: SOH912
_portal_id: required-but-empty
_root_path: https://rt3api-prd.ttaws.com
